rm(list=ls())
library(FLAdvice)
setwd("C:/Projects/m1205/gislaSim/ICES")
source("C:/Sandbox/pkg/FLAdvice/R/lh.R")

# load ICES data
load("data/dbICES.RData")
# What's in it?
names(dbICES)
# "FindZeros" - nada
# "overview" - table of stock and wg - 49 stocks
# "ages" - table of stock, wg, min age and fbar range - why more stocks than overview table (87 of them)
# "ts" - table of stock, wg, then recruitment, biomass, ssb, landings, y-s, fbar through time, 49 stocks
# "id" - table of wg, stock and description of stock (291 stocks)
# "pa" - wg, stock, Flim, Fpa, Blim, Bpa
# "ypr" - stock parameters, everything for BRP object, e.g.  - 39 stocks

# We can use the parameters in ypr to compare against ones generated by lh()
# Don't have to stick to cod can do all species
# Will need LH for all species in all areas

# Add another column to ypr with species
dbICES$ypr <- cbind(dbICES$ypr, species = laply(strsplit(x = as.character(dbICES$ypr$stock), split= "-"),
                function(x) return(x[1])))

wgdata <- melt(dbICES$ypr, id.vars = c("wg", "stock", "age", "species"))

# Probably want to focus on species that we have more than data set for
nstocks <- ddply(ddply(wgdata, .(stock), summarise, species = unique(species)),
                  .(species), summarise, number = length(species))
# Maybe just stick to plaice (4), herring (4), cod (7), haddock (6) and sole (7)
# And just keep m, stock.wt and mat
wgdata <- wgdata[(wgdata$species %in% c("cod","ple","her","sol","had")) &
                  (wgdata$variable %in% c("m", "stock.wt", "mat")),]
# Need to tidy up the factors - plot looks bad atm
wgdata$stock <- factor(wgdata$stock)

# plot up stock.wts, m and mat for each species by age
p <- ggplot(wgdata) + geom_point(aes(x = age, y = value, group = stock, colour = stock)) +
  facet_grid(variable ~ species, scales="free")
# Can we scale the plot by max - comparing weights between stocks is bad

#*******************************************************************************
# Just focus on cod for the moment
wgcod <- wgdata[wgdata$species == "cod",]
# Cod in North Sea is not here...

# Add Linf, K and mat(?) for each stock
# Just make them all the same as NS cod at the moment
ages <- 1:30
NScod_linf <- 132
NScod_k <- 0.2

NScodpar1 <- gislasim(FLPar(linf = NScod_linf))
NScodLH1 <- lh(NScodpar1, age = ages)
NScodpar2 <- gislasim(FLPar(linf = NScod_linf, k = NScod_k))
NScodLH2 <- lh(NScodpar2, age = ages)

# ddply this up
lhcod <-  rbind(
          cbind(wg = "wgnssk", stock = "cod-nsea", lh = "lh1",
               rbind(
                    cbind(variable = "stock.wt", as.data.frame(stock.wt(NScodLH1)/1000)),
                    cbind(variable = "m", as.data.frame(m(NScodLH1))),
                    cbind(variable = "mat", as.data.frame(mat(NScodLH1)))
                    )
              ),
          cbind(wg = "wgnssk", stock = "cod-nsea", lh = "lh2",
               rbind(
                    cbind(variable = "stock.wt", as.data.frame(stock.wt(NScodLH2)/1000)),
                    cbind(variable = "m", as.data.frame(m(NScodLH2))),
                    cbind(variable = "mat", as.data.frame(mat(NScodLH2)))
                    )
              )
          )



# Chop out unwanted columns
lhcod <- lhcod[,c("wg","stock","lh","variable","age","data")]

# Plot against the WG cod data
p <- ggplot(wgcod) + geom_point(aes(x=age, y = value, colour = stock)) +
                     facet_wrap(~variable, scales = "free")
p <- p + geom_line(aes(x=age, y = data, colour = stock, group = lh), data = lhcod)

# Next
add in WG NSea data to dbICES$ypr
get more cod stock LH params (not just NSea)
more levels of LH info (+ LW, mat etc)

# Get Spr0 from WG (in table already or need to put into BRP)
# Get Spr0 from LH with increasing LHinfo
# Compare

# Then turn attention to sel

